#!/usr/bin/env bash
# Refreshes the Cloudflare origin peer policy from Cloudflare's official IP feeds.

set -euo pipefail
umask 022

if [[ ${EUID} -ne 0 ]]; then
    echo "ERROR: run as root" >&2
    exit 1
fi

readonly IPV4_FEED='https://www.cloudflare.com/ips-v4'
readonly IPV6_FEED='https://www.cloudflare.com/ips-v6'
readonly POLICY_DIR='/etc/nginx/cloudflare-policy'
readonly TRUSTED_PROXIES_CONF="${POLICY_DIR}/trusted-proxies.conf"
readonly CIDRS_FILE="${POLICY_DIR}/cidrs.txt"
readonly PEER_MAP_CONF='/etc/nginx/conf.d/cloudflare-peer-map.conf'
readonly FIREWALL_SCRIPT='/usr/local/sbin/apply-cloudflare-origin-firewall'

temp_dir="$(mktemp -d /var/tmp/cloudflare-origin-policy.XXXXXX)"
trap 'rm -rf "${temp_dir}"' EXIT

fetch_feed() {
    local url="$1"
    local destination="$2"
    curl --fail --silent --show-error --location --proto '=https' --tlsv1.2 \
        --connect-timeout 10 --max-time 30 "$url" -o "$destination"
}

fetch_feed "${IPV4_FEED}" "${temp_dir}/ips-v4"
fetch_feed "${IPV6_FEED}" "${temp_dir}/ips-v6"

python3 - "${temp_dir}/ips-v4" "${temp_dir}/ips-v6" > "${temp_dir}/cidrs.txt" <<'PY'
from ipaddress import ip_network
from pathlib import Path
import sys

seen = set()
valid_count = 0
for filename, expected_version in zip(sys.argv[1:], (4, 6), strict=True):
    for raw_line in Path(filename).read_text(encoding="utf-8").splitlines():
        candidate = raw_line.strip()
        if not candidate:
            continue
        try:
            network = ip_network(candidate, strict=True)
        except ValueError as error:
            raise SystemExit(f"Invalid Cloudflare CIDR {candidate!r}: {error}") from error
        if network.version != expected_version:
            raise SystemExit(f"Unexpected IPv{network.version} CIDR in {filename}: {candidate}")
        normalized = network.with_prefixlen
        if normalized not in seen:
            seen.add(normalized)
            print(normalized)
            valid_count += 1

if valid_count == 0:
    raise SystemExit("Cloudflare feeds did not contain any CIDRs")
PY

if [[ ! -s "${temp_dir}/cidrs.txt" ]]; then
    echo "ERROR: Cloudflare feed validation produced no CIDRs" >&2
    exit 1
fi

{
    printf '%s\n' '# Generated by update-cloudflare-origin-policy.sh. Do not edit.'
    while IFS= read -r cidr; do
        printf 'set_real_ip_from %s;\n' "${cidr}"
    done < "${temp_dir}/cidrs.txt"
    printf '%s\n' 'real_ip_header CF-Connecting-IP;' 'real_ip_recursive off;'
} > "${temp_dir}/trusted-proxies.conf"

{
    printf '%s\n' '# Generated by update-cloudflare-origin-policy.sh. Do not edit.'
    printf '%s\n' 'geo $realip_remote_addr $cloudflare_peer_allowed {' '    default 0;' '    127.0.0.1 1;' '    ::1 1;'
    while IFS= read -r cidr; do
        printf '    %s 1;\n' "${cidr}"
    done < "${temp_dir}/cidrs.txt"
    printf '%s\n' '}'
} > "${temp_dir}/cloudflare-peer-map.conf"

cat > "${temp_dir}/apply-cloudflare-origin-firewall" <<'FIREWALL'
#!/usr/bin/env bash
set -euo pipefail

readonly CIDRS_FILE='/etc/nginx/cloudflare-policy/cidrs.txt'

if [[ ${EUID} -ne 0 ]]; then
    echo "ERROR: run as root" >&2
    exit 1
fi
if ! command -v ufw >/dev/null 2>&1; then
    echo "ERROR: ufw is required to apply the Cloudflare origin firewall policy" >&2
    exit 1
fi
if [[ ! -s "${CIDRS_FILE}" ]]; then
    echo "ERROR: missing Cloudflare CIDR policy: ${CIDRS_FILE}" >&2
    exit 1
fi

# Remove policy-managed rules in reverse order so UFW rule numbers stay stable.
while IFS= read -r rule_number; do
    [[ -n "${rule_number}" ]] || continue
    ufw --force delete "${rule_number}" >/dev/null
done < <(ufw status numbered | awk '
    /# Cloudflare origin (HTTP|HTTPS)/ {
        if (match($0, /^[[:space:]]*\[[[:space:]]*[0-9]+[[:space:]]*\]/)) {
            rule_number = substr($0, RSTART, RLENGTH)
            gsub(/[^0-9]/, "", rule_number)
            print rule_number
        }
    }
' | sort -rn)

# Remove legacy broad origin rules before adding the Cloudflare-only policy.
ufw --force delete allow 80/tcp >/dev/null 2>&1 || true
ufw --force delete allow 443/tcp >/dev/null 2>&1 || true
ufw --force delete allow "Nginx HTTP" >/dev/null 2>&1 || true
ufw --force delete allow "Nginx HTTPS" >/dev/null 2>&1 || true
ufw --force delete allow "Nginx Full" >/dev/null 2>&1 || true
ufw allow in on lo comment 'Loopback health probes' >/dev/null

while IFS= read -r cidr; do
    [[ -n "${cidr}" ]] || continue
    ufw allow from "${cidr}" to any port 80 proto tcp comment 'Cloudflare origin HTTP' >/dev/null
    ufw allow from "${cidr}" to any port 443 proto tcp comment 'Cloudflare origin HTTPS' >/dev/null
done < "${CIDRS_FILE}"
FIREWALL

install -d -m 0755 -o root -g root "${POLICY_DIR}" /etc/nginx/conf.d /usr/local/sbin

declare -a targets=("${TRUSTED_PROXIES_CONF}" "${CIDRS_FILE}" "${PEER_MAP_CONF}" "${FIREWALL_SCRIPT}")
declare -a staged=("${temp_dir}/trusted-proxies.conf" "${temp_dir}/cidrs.txt" "${temp_dir}/cloudflare-peer-map.conf" "${temp_dir}/apply-cloudflare-origin-firewall")
declare -a modes=(0644 0644 0644 0700)

backup_policy_files() {
    local index target
    for index in "${!targets[@]}"; do
        target="${targets[$index]}"
        if [[ -e "${target}" ]]; then
            cp -a -- "${target}" "${temp_dir}/backup-${index}"
        else
            : > "${temp_dir}/backup-${index}.missing"
        fi
    done
}

restore_policy_files() {
    local index target restore
    for index in "${!targets[@]}"; do
        target="${targets[$index]}"
        if [[ -f "${temp_dir}/backup-${index}.missing" ]]; then
            rm -f -- "${target}"
            continue
        fi
        restore="${target}.restore.$$"
        cp -a -- "${temp_dir}/backup-${index}" "${restore}"
        mv -f -- "${restore}" "${target}"
    done
}

commit_policy_files() {
    local index target next
    for index in "${!targets[@]}"; do
        target="${targets[$index]}"
        next="${target}.next.$$"
        install -m "${modes[$index]}" -o root -g root "${staged[$index]}" "${next}"
        mv -f -- "${next}" "${target}"
    done
}

backup_policy_files
commit_policy_files

if command -v nginx >/dev/null 2>&1; then
    if ! nginx -t; then
        echo "ERROR: generated Cloudflare policy failed nginx validation; restoring the previous policy" >&2
        restore_policy_files
        nginx -t >/dev/null 2>&1 || true
        exit 1
    fi
    if systemctl is-active --quiet nginx; then
        if ! systemctl reload nginx; then
            echo "ERROR: nginx reload failed; restoring the previous policy" >&2
            restore_policy_files
            nginx -t >/dev/null 2>&1 && systemctl reload nginx || true
            exit 1
        fi
    fi
fi

"${FIREWALL_SCRIPT}"
echo "Cloudflare origin policy updated."